name: Build
on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: npm install
        working-directory: site
      - uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
      - run: wget -O - https://github.com/thedodd/trunk/releases/download/v0.16.0/trunk-x86_64-unknown-linux-gnu.tar.gz | tar xz trunk
      - run: ../trunk build --release --public-url /WebConsole/
        working-directory: site
      - run: wget -O - https://github.com/casey/just/releases/download/1.13.0/just-1.13.0-x86_64-unknown-linux-musl.tar.gz | tar xz just
      - run: ./just build && cp local/WebConsole.phar site/dist
      - uses: actions/upload-pages-artifact@v1
        with:
          path: site/dist
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-20.04
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
